# Generated by Django 3.1.2 on 2020-11-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201101_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
